"""Show contents of all Parquet files generated by the pipelines.

Usage:
    uv run python show_parquet.py
"""

import polars as pl
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "output"

PARQUET_FILES = [
    # XML pipeline
    ("xml/harvest/terminology.parquet", "XML Harvest: Terminology (flat lookup)"),
    ("xml/harvest/objects.parquet", "XML Harvest: Objects (native nested types)"),
    ("xml/transform/objects_enriched.parquet", "XML Transform: Enriched objects"),
    # JSON pipeline
    ("json/harvest/terminology.parquet", "JSON Harvest: Terminology (flat lookup)"),
    ("json/harvest/objects.parquet", "JSON Harvest: Objects (native nested types)"),
    ("json/transform/objects_enriched.parquet", "JSON Transform: Enriched objects"),
]


def main() -> None:
    for rel_path, label in PARQUET_FILES:
        path = OUTPUT_DIR / rel_path
        print(f"\n{'=' * 70}")
        print(f"{label}")
        print(f"  {path}")
        print("=" * 70)

        if not path.exists():
            print("  [not found — run pipeline_xml.py or pipeline_json.py first]")
            continue

        df = pl.read_parquet(path)
        print(f"  Shape: {df.shape[0]} rows x {df.shape[1]} columns")
        print("  Schema:")
        for name, dtype in df.schema.items():
            print(f"    {name}: {dtype}")
        print()
        # Use pl.Config to show full nested content
        with pl.Config(
            tbl_rows=20,
            tbl_cols=20,
            fmt_str_lengths=80,
            tbl_width_chars=120,
        ):
            print(df)


if __name__ == "__main__":
    main()
